AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/metabase/error.rb

Metrics/MethodLength:
  Max: 20
