name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '2.7'
          - '2.6'
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        BUNDLE_CLEAN: 'true'
        BUNDLE_DEPLOYMENT: 'true'
        BUNDLE_JOBS: 4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-ruby${{ matrix.ruby }}-
      - name: Install gems
        run: gem install bundler && bundle install
      - name: Rubocop
        run: bundle exec rubocop
      - name: RSpec
        run: bundle exec rake spec
